[package]
name = "sonduit-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "sonduit"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
chrono = { version = "0.4", features = ["clock"] }
tauri-plugin-notification = "2"
tauri-plugin-store = "2.4.1"
tauri-plugin-log = "2.7.1"
tauri-plugin-process = "2.3.1"

[features]
# This feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
