[package]
name = "sonduit-desktop"
description = "Sonduit desktop shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "sonduit"
path = "src/main.rs"

[dependencies]
sonduit-core.workspace = true
sonduit-transport.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
chrono = { version = "0.4", features = ["clock"] }
tauri-plugin-notification = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-store = "2.4.1"
tauri-plugin-log = "2.7.1"
tauri-plugin-process = "2.3.1"

[features]
# Used for production builds, or when devPath points at the filesystem.
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
