#!/usr/bin/env node
/**
 * Validates commit messages against the project's two rules:
 *
 *   1. The subject line must be pure ASCII.
 *   2. The subject must be a Conventional Commits 1.0.0 header, with a type
 *      and scope drawn from the project's fixed lists.
 *
 * Usage:
 *   node tools/lint/check-commits.mjs <range>      e.g. origin/develop..HEAD
 *   node tools/lint/check-commits.mjs --message <file>
 *
 * With no argument it checks HEAD alone, which is what a local pre-push hook
 * wants.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const TYPES = [
  'feat',
  'fix',
  'perf',
  'refactor',
  'docs',
  'test',
  'build',
  'ci',
  'chore',
  'revert',
];

const SCOPES = [
  'core',
  'transport',
  'capture-win',
  'playback-android',
  'desktop',
  'android',
  'driver',
  'protocol',
  'ci',
  'docs',
  'deps',
  // The build and version tooling under tools/. A real part of the repository
  // that had no scope, so commits touching it had nothing correct to say.
  'tools',
];

/**
 * Commits at or before this one are not checked.
 *
 * See the file itself for why it exists. Read lazily and tolerantly: a missing
 * baseline means check everything, which is the safe direction.
 */
const BASELINE_FILE = 'tools/lint/commit-baseline';

const MAX_SUBJECT = 72;

// type(scope)!: subject   -- scope and the breaking-change bang are optional
const HEADER = /^(?<type>[a-z]+)(?:\((?<scope>[a-z0-9-]+)\))?(?<bang>!)?: (?<subject>.+)$/;

function firstNonAscii(text) {
  for (let i = 0; i < text.length; i += 1) {
    const code = text.codePointAt(i);
    if (code > 0x7f) {
      return { index: i, char: text[i], code };
    }
  }
  return null;
}

/** Check one full commit message. Returns an array of problem strings. */
export function checkMessage(message) {
  const problems = [];
  const lines = message.split(/\r?\n/);
  const subject = lines[0] ?? '';

  if (subject.trim() === '') {
    return ['subject line is empty'];
  }

  // A merge or revert commit generated by git is exempt from the header shape,
  // but still may not carry non-ASCII.
  const isGenerated = /^(Merge|Revert) /.test(subject);

  const nonAscii = firstNonAscii(subject);
  if (nonAscii) {
    const code = `U+${nonAscii.code.toString(16).toUpperCase().padStart(4, '0')}`;
    problems.push(
      `subject contains non-ASCII ${JSON.stringify(nonAscii.char)} (${code}) at column ${nonAscii.index + 1}`,
    );
  }

  if (isGenerated) {
    return problems;
  }

  const match = HEADER.exec(subject);
  if (!match) {
    problems.push(
      'subject is not a Conventional Commit header: expected "<type>(<scope>): <subject>"',
    );
    return problems;
  }

  const { type, scope, subject: text } = match.groups;

  if (!TYPES.includes(type)) {
    problems.push(`unknown type "${type}", expected one of: ${TYPES.join(', ')}`);
  }

  if (scope !== undefined && !SCOPES.includes(scope)) {
    problems.push(`unknown scope "${scope}", expected one of: ${SCOPES.join(', ')}`);
  }

  if (subject.length > MAX_SUBJECT) {
    problems.push(`subject is ${subject.length} characters, limit is ${MAX_SUBJECT}`);
  }

  if (text.endsWith('.')) {
    problems.push('subject must not end with a period');
  }

  if (/^[A-Z]/.test(text)) {
    problems.push('subject must start lowercase');
  }

  // "wip" and "fix typo" are squash-before-merge smells, not develop history.
  if (/^(wip\b|fix typo|typo\b|update\b\s*$)/i.test(text)) {
    problems.push(`subject "${text}" looks like a work-in-progress commit; squash before merging`);
  }

  return problems;
}

function commitsInRange(range) {
  const output = execFileSync('git', ['log', '--format=%H', range], { encoding: 'utf8' });
  return output.split('\n').filter(Boolean);
}

/** The baseline commit, or null when there is none or it is not in this tree. */
function baselineCommit() {
  let sha;
  try {
    sha = readFileSync(BASELINE_FILE, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#'))
      .pop();
  } catch {
    return null;
  }
  if (!sha || !/^[0-9a-f]{40}$/.test(sha)) return null;

  try {
    // A shallow clone will not have it. Checking everything is then correct.
    execFileSync('git', ['cat-file', '-e', `${sha}^{commit}`], { stdio: 'ignore' });
  } catch {
    return null;
  }
  return sha;
}

/** Drop commits that are ancestors of, or equal to, the baseline. */
function afterBaseline(hashes) {
  const baseline = baselineCommit();
  if (!baseline) return hashes;

  return hashes.filter((hash) => {
    if (hash === baseline) return false;
    try {
      execFileSync('git', ['merge-base', '--is-ancestor', hash, baseline], { stdio: 'ignore' });
      return false;
    } catch {
      return true;
    }
  });
}

function messageOf(hash) {
  return execFileSync('git', ['log', '-1', '--format=%B', hash], { encoding: 'utf8' });
}

function main() {
  const args = process.argv.slice(2);

  if (args[0] === '--message') {
    const message = readFileSync(args[1], 'utf8');
    const problems = checkMessage(message);
    if (problems.length > 0) {
      console.error(`Invalid commit message:\n  ${message.split('\n')[0]}\n`);
      for (const problem of problems) console.error(`  - ${problem}`);
      process.exit(1);
    }
    console.log('OK: commit message is valid.');
    return;
  }

  const range = args[0] ?? 'HEAD~1..HEAD';
  let hashes;
  try {
    hashes = afterBaseline(commitsInRange(range));
  } catch (error) {
    console.error(`Could not read commits in range "${range}": ${error.message}`);
    process.exit(1);
  }

  if (hashes.length === 0) {
    console.log(`OK: no commits in range ${range}.`);
    return;
  }

  let failed = 0;
  for (const hash of hashes) {
    const message = messageOf(hash);
    const problems = checkMessage(message);
    if (problems.length > 0) {
      failed += 1;
      console.error(`\n${hash.slice(0, 8)}  ${message.split('\n')[0]}`);
      for (const problem of problems) console.error(`  - ${problem}`);
    }
  }

  if (failed > 0) {
    console.error(`\n${failed} of ${hashes.length} commit(s) invalid.`);
    console.error('Format: <type>(<scope>): <subject>');
    console.error(`  types:  ${TYPES.join(' ')}`);
    console.error(`  scopes: ${SCOPES.join(' ')}`);
    console.error('  subject: imperative, lowercase, no trailing period, <= 72 chars total');
    process.exit(1);
  }

  console.log(`OK: ${hashes.length} commit(s) in ${range} are valid.`);
}

main();
